package it.unicam.cs.mpgc.rpg122711.domain.world;

public enum EventType {
    ENTERED_RUINS,
    ANALYZED_RUINS,
    IGNORED_RUINS,
    ENTERED_CHURCH,
    DIARY_FOUND,
    RUNES_READ,
    DISTORTION_ANALYZED,
    TRACKS_FOLLOWED,
    FOREST_OBSERVED,
    ECHO_FOLLOWED,
    FOREST_ANALYZED,
    FOREST_TRAVERSED,
    MEMORY_CONTACT,
    SANCTUARY_DISCOVERED,
    MEMORY_CORE_FOUND,
    CUSTODIAN_MENTIONED,
    CUSTODIAN_MAGIC_DISCOVERED0,
    MEMORY_STORAGE_DISCOVERED,
    CUSTODIAN_TRACKS_FOUND,
    OBLIVION_TRUTH_REVEALED,
    OBLIVION_STRUCTURE_ANALYZED,
    OBLIVION_PATH_WALKED,
    ENTERED_OBLIVION_CORE
}