package it.unicam.cs.mpgc.rpg122711.domain.world;

/**
 * Enumerazione degli eventi di gioco cardine utilizzati per poi
 * tracciare la progressione storica e le scelte narrative del giocatore.
 */
public enum EventType {

    ENTERED_RUINS,
    ENTERED_CHURCH,
    DIARY_FOUND,
    RUNES_READ,
    DISTORTION_ANALYZED,
    TRACKS_FOLLOWED,

    FOREST_OBSERVED,
    FOREST_ANALYZED,
    FOREST_TRAVERSED,
    ECHO_FOLLOWED,
    MEMORY_CONTACT,

    SANCTUARY_DISCOVERED,
    SANCTUARY_EXPLORED,
    MEMORY_CORE_FOUND,

    CUSTODIAN_MENTIONED,
    CUSTODIAN_TRACKS_FOUND,
    CUSTODIAN_ENCOUNTERED,
    CUSTODIAN_MAGIC_DISCOVERED,
    CUSTODIAN_REVEAL,

    MEMORY_STORAGE_DISCOVERED,
    MEMORY_ARCHIVE_OBSERVED,

    LIBRARY_FOUND,
    OBLIVION_BREACH,

    OBLIVION_TRUTH_REVEALED,
    OBLIVION_PATH_WALKED
}