package it.unicam.cs.mpgc.rpg122711.domain.world;

/**
 * Eventi di gioco utilizzati per tracciare la progressione narrativa.
 * Ogni evento rappresenta un fatto irripetibile nel mondo.
 */
public enum EventType {

    // MISSIONE 1
    ENTERED_RUINS,
    ENTERED_CHURCH,
    DIARY_FOUND,
    RUNES_READ,
    DISTORTION_ANALYZED,
    TRACKS_FOLLOWED,

    // MISSIONE 2
    FOREST_OBSERVED,
    FOREST_ANALYZED,
    FOREST_TRAVERSED,
    ECHO_FOLLOWED,
    MEMORY_CONTACT,

    // MISSIONE 3
    SANCTUARY_DISCOVERED,
    MEMORY_CORE_FOUND,

    CUSTODIAN_MENTIONED,
    CUSTODIAN_TRACKS_FOUND,
    CUSTODIAN_ENCOUNTERED,
    CUSTODIAN_MAGIC_DISCOVERED,
    CUSTODIAN_REVEAL,

    MEMORY_STORAGE_DISCOVERED,
    MEMORY_ARCHIVE_OBSERVED,

    // MISSIONE 4
    LIBRARY_FOUND,
    OBLIVION_BREACH,

    // FINALE
    OBLIVION_TRUTH_REVEALED,
    OBLIVION_PATH_WALKED
}